import type { GameData } from "../src";

export const fixture: GameData = {
  schemaVersion: 1,
  seeds: ["一", "丨", "丿", "㇏"],
  elements: {
    一: { kind: "stroke", pinyin: [], gloss: "horizontal", name: "横", depth: 0, terminal: false },
    丨: { kind: "stroke", pinyin: [], gloss: "vertical", name: "竖", depth: 0, terminal: false },
    丿: {
      kind: "stroke",
      pinyin: [],
      gloss: "left-falling",
      name: "撇",
      depth: 0,
      terminal: false,
    },
    "㇏": {
      kind: "stroke",
      pinyin: [],
      gloss: "right-falling",
      name: "捺",
      depth: 0,
      terminal: false,
    },
    十: { kind: "character", pinyin: ["shí"], gloss: "ten", depth: 1, terminal: false },
    八: { kind: "character", pinyin: ["bā"], gloss: "eight", depth: 1, terminal: true },
    人: { kind: "character", pinyin: ["rén"], gloss: "person", depth: 1, terminal: false },
    入: { kind: "character", pinyin: ["rù"], gloss: "enter", depth: 1, terminal: true },
    木: { kind: "character", pinyin: ["mù"], gloss: "tree", depth: 2, terminal: false },
    林: { kind: "character", pinyin: ["lín"], gloss: "grove", depth: 3, terminal: false },
    森: { kind: "character", pinyin: ["sēn"], gloss: "forest", depth: 4, terminal: true },
    川: { kind: "character", pinyin: ["chuān"], gloss: "river", depth: 1, terminal: true },
    亻: { kind: "component", pinyin: [], gloss: "person", depth: 1, terminal: false },
    休: { kind: "character", pinyin: ["xiū"], gloss: "rest", depth: 3, terminal: true },
  },
  recipes: [
    ["十", "⿻", "一", "丨"],
    ["八", "⿰", "丿", "㇏"],
    ["人", "⿻", "丿", "㇏"],
    ["入", "⿻", "㇏", "丿"],
    ["木", "⿻", "十", "八"],
    ["林", "⿰", "木", "木"],
    ["森", "⿱", "木", "林"],
    ["川", "⿲", "丿", "丨", "丨"],
    ["亻", "⿰", "丿", "丨"],
    ["休", "⿰", "亻", "木"],
  ],
  variants: [{ form: "亻", base: "人", position: "left" }],
  collections: [{ id: "trees", title: "Trees", titleZh: "木林森", members: ["木", "林", "森"] }],
  sources: [],
};
